"""Dashboard: static HTML index over runs/ + the cost ledger."""
from __future__ import annotations

import datetime as _dt
import glob
import json
import os

from . import ledger

CSS = """
body{font-family:system-ui,-apple-system,sans-serif;max-width:1100px;margin:2rem auto;
padding:0 1rem;color:#1a1a1a;background:#fafafa}
.cards{display:flex;gap:1rem;flex-wrap:wrap;margin:1rem 0}
.card{background:#fff;border:1px solid #e2e2e2;border-radius:8px;padding:1rem 1.25rem;min-width:150px}
.card b{font-size:1.6rem;display:block}
.pass{color:#137333}.fail{color:#b3261e}
table{width:100%;border-collapse:collapse;background:#fff}
th,td{text-align:left;padding:.5rem .75rem;border-bottom:1px solid #eee;font-size:.9rem}
th{background:#f3f3f3}
a{color:#0b57d0}
.muted{color:#666;font-size:.85rem}
"""


def _load_runs(runs_root: str) -> list[dict]:
    runs = []
    for path in sorted(glob.glob(os.path.join(runs_root, "*", "run.json")), reverse=True):
        try:
            with open(path, encoding="utf-8") as f:
                runs.append(json.load(f))
        except Exception:
            continue
    return runs


def build(runs_root: str, out_dir: str) -> str:
    runs = _load_runs(runs_root)
    summary = ledger.summarize()
    passed = sum(1 for r in runs if r.get("status") == "passed")

    def ts(r: dict) -> str:
        try:
            return _dt.datetime.fromtimestamp(r["started"], _dt.timezone.utc).strftime(
                "%Y-%m-%d %H:%M UTC")
        except Exception:
            return "—"

    rows = []
    for r in runs:
        d = os.path.basename(r.get("run_dir", ""))
        badge = "pass" if r.get("status") == "passed" else "fail"
        diag = ""
        if r.get("diagnosis"):
            dg = r["diagnosis"]
            diag = f"<br><span class='muted'>dx: {(dg.get('likely_cause') or '')[:90]}</span>"
        rows.append(
            f"<tr><td>{ts(r)}</td><td>{r.get('flow_name', '—')}</td>"
            f"<td class='{badge}'><b>{r.get('status', '?').upper()}</b></td>"
            f"<td>{r.get('duration_ms', '—')}ms</td>"
            f"<td><a href='../runs/{d}/REPORT.md'>{d}</a>{diag}</td></tr>")

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>qaloop dashboard</title><style>{CSS}</style></head><body>
<h1>qaloop dashboard</h1>
<p class="muted">deterministic flows + on-failure investigator. regenerated by
<code>qaloop dashboard</code>.</p>
<div class="cards">
<div class="card"><b>{len(runs)}</b>runs</div>
<div class="card"><b class="pass">{passed}</b>passed</div>
<div class="card"><b class="fail">{len(runs) - passed}</b>failed</div>
<div class="card"><b>{summary['investigations']}</b>investigations</div>
<div class="card"><b>${summary['total_cost_usd_est']}</b>est. LLM cost</div>
</div>
<h2>Runs</h2>
<table><tr><th>time</th><th>flow</th><th>status</th><th>duration</th><th>report</th></tr>
{''.join(rows) if rows else '<tr><td colspan=5 class="muted">no runs yet</td></tr>'}
</table>
<h2>Cost ledger</h2>
<p>scripted runs: {summary['scripted_runs']} at ~$0 &nbsp;·&nbsp;
investigations: {summary['investigations']} at
${summary['investigation_cost_usd_est']} est.</p>
<p class="muted">The hybrid working as designed: the deterministic runner is
free; the agent only spends when a flow fails.</p>
</body></html>"""
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "index.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path
